codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 0..100
  status:
    project:
      default:
        target: auto
        threshold: 1
    patch:
      default:
        target: auto
        threshold: 1

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
