codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 0..100
  ignore:
    - "packages/client/tests/e2e/**"
    - "packages/client/tests/integration/*.integration.test.ts"
    - "packages/client/tests/integration/visual/**"
    - "packages/client/tests/visual/**"
    - "tests/infrastructure/thematic-summary.paths.test.ts"
  status:
    project:
      default:
        target: auto
        threshold: 1
    patch:
      default:
        target: auto
        threshold: 1

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
