# PNPM Workspace Configuration for CritGenius Listener
# Defines the monorepo structure with client, server, and shared packages

packages:
  # Core application packages
  - 'packages/*'
  
  # Additional workspace directories (if any)
  # - 'tools/*'
  # - 'scripts/*'

# Catalog for shared dependency versions across workspace
catalog:
  # React ecosystem
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  
  # TypeScript and build tools
  typescript: ^5.6.3
  vite: ^5.4.11
  vitest: ^2.1.4
  '@vitejs/plugin-react': ^4.3.3
  
  # Linting and formatting
  eslint: ^9.15.0
  prettier: ^3.3.3
  '@typescript-eslint/eslint-plugin': ^8.15.0
  '@typescript-eslint/parser': ^8.15.0
  
  # Node.js and Express
  express: ^4.21.1
  '@types/express': ^5.0.0
  cors: ^2.8.5
  '@types/cors': ^2.8.17
  
  # File handling and utilities
  multer: ^1.4.5-lts.1
  '@types/multer': ^1.4.12
  
  # Audio processing (for future implementation)
  # fluent-ffmpeg: ^2.1.3
  # '@types/fluent-ffmpeg': ^2.1.26
  
  # Testing utilities
  '@testing-library/react': ^16.0.1
  '@testing-library/jest-dom': ^6.6.3
  jsdom: ^25.0.1
  
  # Development utilities
  nodemon: ^3.1.7
  concurrently: ^9.1.0
  rimraf: ^6.0.1