# GitHub Issue Template Configuration
# CritGenius: Listener - D&D Audio Capture & Transcription System

# Disable blank issues to ensure proper categorization
blank_issues_enabled: false

# Contact links for issues that don't fit templates
contact_links:
  - name: 🎲 D&D Community Discussion
    url: https://github.com/crit-genius/listener/discussions
    about: Join the community discussion for general D&D integration ideas, gameplay questions, and collaborative brainstorming.

  - name: 📚 Documentation & Usage Questions
    url: https://github.com/crit-genius/listener/discussions/categories/q-a
    about: Ask questions about setup, configuration, usage, or D&D session integration in our Q&A section.

  - name: 🚀 Feature Ideas & Brainstorming
    url: https://github.com/crit-genius/listener/discussions/categories/ideas
    about: Share early-stage ideas for D&D features, CritGenius ecosystem integration, or content creator tools.

  - name: 🎧 Audio Hardware Compatibility
    url: https://github.com/crit-genius/listener/discussions/categories/hardware
    about: Discuss microphone compatibility, audio device optimization, and hardware setup recommendations.

  - name: 🔒 Security & Privacy Concerns
    url: https://github.com/crit-genius/listener/security/advisories
    about: Report security vulnerabilities privately through GitHub's security advisory system.

  - name: 📊 Performance Optimization Discussion
    url: https://github.com/crit-genius/listener/discussions/categories/performance
    about: Discuss performance optimization strategies, share benchmarks, and collaborate on audio processing improvements.

# Template selection guidance
# This helps users choose the right template for their issue type
template_chooser:
  # Bug Report Template Selection
  bug_report_triggers:
    - "audio not working"
    - "microphone"
    - "transcription error"
    - "speaker identification"
    - "AssemblyAI"
    - "latency"
    - "connection failed"
    - "browser compatibility"
    - "Web Audio API"
    - "character mapping"
    - "D&D terminology"
    - "crash"
    - "freeze"
    - "error message"
    - "not responding"

  # Feature Request Template Selection
  feature_request_triggers:
    - "enhancement"
    - "new feature"
    - "improvement"
    - "suggestion"
    - "D&D integration"
    - "character sheet"
    - "campaign"
    - "export"
    - "streaming"
    - "accessibility"
    - "mobile support"
    - "API endpoint"
    - "webhook"
    - "notification"
    - "dashboard"

  # Performance Issue Template Selection
  performance_triggers:
    - "slow"
    - "lag"
    - "delay"
    - "high CPU"
    - "memory leak"
    - "high memory"
    - "bandwidth"
    - "latency"
    - "timeout"
    - "connection slow"
    - "response time"
    - "optimization"
    - "performance"
    - "stuttering"
    - "dropping audio"

# Issue labeling automation based on template selection and content
auto_labeling:
  # Bug Report Labels
  bug_report:
    default_labels:
      - "bug"
      - "needs-triage"
    content_based_labels:
      audio_related:
        keywords: ["microphone", "audio", "Web Audio API", "sound", "recording"]
        labels: ["component:audio"]
      transcription_related:
        keywords:
          ["AssemblyAI", "transcription", "speech-to-text", "recognition"]
        labels: ["component:transcription"]
      ui_related:
        keywords: ["interface", "UI", "button", "display", "responsive"]
        labels: ["component:ui"]
      browser_related:
        keywords: ["Chrome", "Firefox", "Safari", "Edge", "browser"]
        labels: ["platform:browser"]
      dnd_related:
        keywords: ["D&D", "character", "campaign", "spell", "dice"]
        labels: ["domain:dnd"]
      privacy_related:
        keywords: ["privacy", "GDPR", "consent", "data protection"]
        labels: ["component:privacy"]

  # Feature Request Labels
  feature_request:
    default_labels:
      - "enhancement"
      - "needs-triage"
    priority_based_labels:
      critical:
        keywords: ["critical", "blocking", "urgent"]
        labels: ["priority:critical"]
      high:
        keywords: ["high priority", "important", "major"]
        labels: ["priority:high"]
      medium:
        keywords: ["medium", "moderate", "nice to have"]
        labels: ["priority:medium"]
      low:
        keywords: ["low priority", "future", "someday"]
        labels: ["priority:low"]
    feature_area_labels:
      ecosystem_integration:
        keywords: ["Prompter", "LLM", "Publisher", "ecosystem"]
        labels: ["epic:ecosystem"]
      content_creator:
        keywords: ["streaming", "export", "content creator", "OBS"]
        labels: ["epic:content-creator"]
      accessibility:
        keywords: ["accessibility", "screen reader", "keyboard", "a11y"]
        labels: ["epic:accessibility"]

  # Performance Issue Labels
  performance_issue:
    default_labels:
      - "performance"
      - "needs-triage"
    severity_based_labels:
      critical_performance:
        keywords: ["unusable", "crash", "freeze", "critical"]
        labels: ["severity:critical"]
      high_performance:
        keywords: ["major delay", "significant", "high impact"]
        labels: ["severity:high"]
      medium_performance:
        keywords: ["noticeable", "moderate", "manageable"]
        labels: ["severity:medium"]
      low_performance:
        keywords: ["minor", "slight", "optimization"]
        labels: ["severity:low"]
    performance_category_labels:
      latency:
        keywords: ["latency", "delay", "response time", "lag"]
        labels: ["perf:latency"]
      memory:
        keywords: ["memory", "RAM", "leak", "usage"]
        labels: ["perf:memory"]
      cpu:
        keywords: ["CPU", "processor", "high usage", "freeze"]
        labels: ["perf:cpu"]
      network:
        keywords: ["network", "bandwidth", "connection", "timeout"]
        labels: ["perf:network"]

# Issue assignment rules
assignment_rules:
  # Component-based assignment
  audio_issues:
    triggers: ["component:audio", "Web Audio API", "microphone"]
    assign_to: "audio-team"

  transcription_issues:
    triggers: ["component:transcription", "AssemblyAI", "speech-to-text"]
    assign_to: "ai-integration-team"

  ui_issues:
    triggers: ["component:ui", "frontend", "React", "interface"]
    assign_to: "frontend-team"

  performance_issues:
    triggers: ["performance", "optimization", "latency"]
    assign_to: "performance-team"

  # Priority-based assignment
  critical_issues:
    triggers: ["priority:critical", "severity:critical"]
    assign_to: "tech-lead"
    escalate: true

  security_issues:
    triggers: ["security", "vulnerability", "privacy"]
    assign_to: "security-team"
    private: true

# Issue lifecycle automation
lifecycle_rules:
  # Stale issue management
  stale_issues:
    days_inactive: 30
    warning_label: "stale"
    close_after: 7
    exclude_labels: ["priority:critical", "priority:high", "in-progress"]

  # Duplicate issue handling
  duplicate_detection:
    similarity_threshold: 0.85
    auto_label: "possible-duplicate"
    require_manual_review: true

  # Issue validation
  validation_rules:
    bug_reports:
      required_fields:
        ["reproduction_steps", "expected_behavior", "actual_behavior"]
      require_environment_info: true

    performance_issues:
      required_fields: ["performance_metrics", "system_specs"]
      require_benchmarks: true

    feature_requests:
      required_fields: ["problem_description", "proposed_solution"]
      require_use_case: true

# Project integration
project_integration:
  # GitHub Projects integration
  default_project: "CritGenius: Listener Development"

  # Board automation
  board_columns:
    new_issues: "🔍 Triage"
    in_progress: "🔨 In Development"
    review: "👀 Review"
    testing: "🧪 Testing"
    done: "✅ Complete"

  # Milestone automation
  milestone_rules:
    bug_fixes: "Bug Fixes & Stability"
    features: "Feature Development"
    performance: "Performance & Optimization"
    documentation: "Documentation & DevEx"

# Notification settings
notifications:
  # Team notifications
  critical_issues:
    notify: ["tech-lead", "product-owner"]
    channels: ["slack", "email"]

  performance_issues:
    notify: ["performance-team", "tech-lead"]
    channels: ["slack"]

  security_issues:
    notify: ["security-team", "tech-lead", "product-owner"]
    channels: ["secure-slack", "email"]
    private: true

  # Community notifications
  dnd_features:
    notify: ["community-manager"]
    channels: ["community-discord"]

  # Stakeholder updates
  weekly_summary:
    recipients: ["product-owner", "stakeholders"]
    format: "email"
    include_metrics: true

# Quality gates
quality_requirements:
  # Code review requirements
  pull_requests:
    require_review: true
    min_reviewers: 1
    require_audio_team_review: ["component:audio"]
    require_security_review: ["component:privacy", "security"]

  # Testing requirements
  testing_gates:
    unit_tests: "required"
    integration_tests: "required_for_features"
    performance_tests: "required_for_performance_changes"
    cross_browser_tests: "required_for_ui_changes"

  # Documentation requirements
  documentation_gates:
    api_changes: "required"
    feature_additions: "required"
    breaking_changes: "required"
    setup_changes: "required"

# Analytics and reporting
analytics:
  # Issue metrics
  track_metrics:
    - "time_to_first_response"
    - "time_to_resolution"
    - "issue_volume_by_type"
    - "performance_issue_trends"
    - "user_satisfaction_scores"

  # Performance tracking
  performance_sla:
    critical_response_time: "2 hours"
    high_response_time: "24 hours"
    medium_response_time: "3 days"
    low_response_time: "1 week"

  # Reporting frequency
  reports:
    daily: ["critical_issues", "new_performance_issues"]
    weekly: ["issue_summary", "team_workload", "user_feedback"]
    monthly: ["trend_analysis", "performance_metrics", "community_health"]

# Template maintenance
template_maintenance:
  review_frequency: "quarterly"
  update_triggers:
    - "new_technology_adoption"
    - "performance_requirement_changes"
    - "user_feedback_patterns"
    - "community_growth_milestones"

  version_control:
    track_changes: true
    require_approval: true
    test_templates: "staging_environment"
